from dataclasses import dataclass
from enum import Enum

from PokemonType import PokemonType

@dataclass
class PokemonMoveData:
    id: int
    power: int
    ptype: PokemonType
    accuracy: int
    max_pp: int


class PokemonMoves(Enum):
    POUND = PokemonMoveData(id=0x01, power=40, ptype=PokemonType.NORMAL, accuracy=100, max_pp=35)
    KARATE_CHOP = PokemonMoveData(id=0x02, power=50, ptype=PokemonType.NORMAL, accuracy=100, max_pp=25)
    DOUBLESLAP = PokemonMoveData(id=0x03, power=15, ptype=PokemonType.NORMAL, accuracy=85, max_pp=10)
    COMET_PUNCH = PokemonMoveData(id=0x04, power=18, ptype=PokemonType.NORMAL, accuracy=85, max_pp=15)
    MEGA_PUNCH = PokemonMoveData(id=0x05, power=80, ptype=PokemonType.NORMAL, accuracy=85, max_pp=20)
    PAY_DAY = PokemonMoveData(id=0x06, power=40, ptype=PokemonType.NORMAL, accuracy=100, max_pp=20)
    FIRE_PUNCH = PokemonMoveData(id=0x07, power=75, ptype=PokemonType.FIRE, accuracy=100, max_pp=15)
    ICE_PUNCH = PokemonMoveData(id=0x08, power=75, ptype=PokemonType.ICE, accuracy=100, max_pp=15)
    THUNDERPUNCH = PokemonMoveData(id=0x09, power=75, ptype=PokemonType.ELECTRIC, accuracy=100, max_pp=15)
    SCRATCH = PokemonMoveData(id=0x0a, power=40, ptype=PokemonType.NORMAL, accuracy=100, max_pp=35)
    VICEGRIP = PokemonMoveData(id=0x0b, power=55, ptype=PokemonType.NORMAL, accuracy=100, max_pp=30)
    GUILLOTINE = PokemonMoveData(id=0x0c, power=1, ptype=PokemonType.NORMAL, accuracy=30,  max_pp=5)
    RAZOR_WIND = PokemonMoveData(id=0x0d, power=80, ptype=PokemonType.NORMAL, accuracy=75, max_pp=10)
    SWORDS_DANCE = PokemonMoveData(id=0x0e, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=30)
    CUT = PokemonMoveData(id=0x0f, power=50, ptype=PokemonType.NORMAL, accuracy=95, max_pp=30)
    GUST = PokemonMoveData(id=0x10, power=40, ptype=PokemonType.NORMAL, accuracy=100, max_pp=35)
    WING_ATTACK = PokemonMoveData(id=0x11, power=35, ptype=PokemonType.FLYING, accuracy=100, max_pp=35)
    WHIRLWIND = PokemonMoveData(id=0x12, power=0, ptype=PokemonType.NORMAL, accuracy=85, max_pp=20)
    FLY = PokemonMoveData(id=0x13, power=70, ptype=PokemonType.FLYING, accuracy=95, max_pp=15)
    BIND = PokemonMoveData(id=0x14, power=15, ptype=PokemonType.NORMAL, accuracy=75, max_pp=20)
    SLAM = PokemonMoveData(id=0x15, power=80, ptype=PokemonType.NORMAL, accuracy=75, max_pp=20)
    VINE_WHIP = PokemonMoveData(id=0x16, power=35, ptype=PokemonType.GRASS, accuracy=100, max_pp=10)
    STOMP = PokemonMoveData(id=0x17, power=65, ptype=PokemonType.NORMAL, accuracy=100, max_pp=20)
    DOUBLE_KICK = PokemonMoveData(id=0x18, power=30, ptype=PokemonType.FIGHTING, accuracy=100, max_pp=30)
    MEGA_KICK = PokemonMoveData(id=0x19, power=120, ptype=PokemonType.NORMAL, accuracy=75,  max_pp=5)
    JUMP_KICK = PokemonMoveData(id=0x1a, power=70, ptype=PokemonType.FIGHTING, accuracy=95, max_pp=25)
    ROLLING_KICK = PokemonMoveData(id=0x1b, power=60, ptype=PokemonType.FIGHTING, accuracy=85, max_pp=15)
    SAND_ATTACK = PokemonMoveData(id=0x1c, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=15)
    HEADBUTT = PokemonMoveData(id=0x1d, power=70, ptype=PokemonType.NORMAL, accuracy=100, max_pp=15)
    HORN_ATTACK = PokemonMoveData(id=0x1e, power=65, ptype=PokemonType.NORMAL, accuracy=100, max_pp=25)
    FURY_ATTACK = PokemonMoveData(id=0x1f, power=15, ptype=PokemonType.NORMAL, accuracy=85, max_pp=20)
    HORN_DRILL = PokemonMoveData(id=0x20, power=1, ptype=PokemonType.NORMAL, accuracy=30,  max_pp=5)
    TACKLE = PokemonMoveData(id=0x21, power=35, ptype=PokemonType.NORMAL, accuracy=95, max_pp=35)
    BODY_SLAM = PokemonMoveData(id=0x22, power=85, ptype=PokemonType.NORMAL, accuracy=100, max_pp=15)
    WRAP = PokemonMoveData(id=0x23, power=15, ptype=PokemonType.NORMAL, accuracy=85, max_pp=20)
    TAKE_DOWN = PokemonMoveData(id=0x24, power=90, ptype=PokemonType.NORMAL, accuracy=85, max_pp=20)
    THRASH = PokemonMoveData(id=0x25, power=90, ptype=PokemonType.NORMAL, accuracy=100, max_pp=20)
    DOUBLE_EDGE = PokemonMoveData(id=0x26, power=100, ptype=PokemonType.NORMAL, accuracy=100, max_pp=15)
    TAIL_WHIP = PokemonMoveData(id=0x27, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=30)
    POISON_STING = PokemonMoveData(id=0x28, power=15, ptype=PokemonType.POISON, accuracy=100, max_pp=35)
    TWINEEDLE = PokemonMoveData(id=0x29, power=25, ptype=PokemonType.BUG, accuracy=100, max_pp=20)
    PIN_MISSILE = PokemonMoveData(id=0x2a, power=14, ptype=PokemonType.BUG, accuracy=85, max_pp=20)
    LEER = PokemonMoveData(id=0x2b, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=30)
    BITE = PokemonMoveData(id=0x2c, power=60, ptype=PokemonType.NORMAL, accuracy=100, max_pp=25)
    GROWL = PokemonMoveData(id=0x2d, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=40)
    ROAR = PokemonMoveData(id=0x2e, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=20)
    SING = PokemonMoveData(id=0x2f, power=0, ptype=PokemonType.NORMAL, accuracy=55, max_pp=15)
    SUPERSONIC = PokemonMoveData(id=0x30, power=0, ptype=PokemonType.NORMAL, accuracy=55, max_pp=20)
    SONICBOOM = PokemonMoveData(id=0x31, power=1, ptype=PokemonType.NORMAL, accuracy=90, max_pp=20)
    DISABLE = PokemonMoveData(id=0x32, power=0, ptype=PokemonType.NORMAL, accuracy=55, max_pp=20)
    ACID = PokemonMoveData(id=0x33, power=40, ptype=PokemonType.POISON, accuracy=100, max_pp=30)
    EMBER = PokemonMoveData(id=0x34, power=40, ptype=PokemonType.FIRE, accuracy=100, max_pp=25)
    FLAMETHROWER = PokemonMoveData(id=0x35, power=95, ptype=PokemonType.FIRE, accuracy=100, max_pp=15)
    MIST = PokemonMoveData(id=0x36, power=0, ptype=PokemonType.ICE, accuracy=100, max_pp=30)
    WATER_GUN = PokemonMoveData(id=0x37, power=40, ptype=PokemonType.WATER, accuracy=100, max_pp=25)
    HYDRO_PUMP = PokemonMoveData(id=0x38, power=120, ptype=PokemonType.WATER, accuracy=80,  max_pp=5)
    SURF = PokemonMoveData(id=0x39, power=95, ptype=PokemonType.WATER, accuracy=100, max_pp=15)
    ICE_BEAM = PokemonMoveData(id=0x3a, power=95, ptype=PokemonType.ICE, accuracy=100, max_pp=10)
    BLIZZARD = PokemonMoveData(id=0x3b, power=120, ptype=PokemonType.ICE, accuracy=90,  max_pp=5)
    PSYBEAM = PokemonMoveData(id=0x3c, power=65, ptype=PokemonType.PSYCHIC, accuracy=100, max_pp=20)
    BUBBLEBEAM = PokemonMoveData(id=0x3d, power=65, ptype=PokemonType.WATER, accuracy=100, max_pp=20)
    AURORA_BEAM = PokemonMoveData(id=0x3e, power=65, ptype=PokemonType.ICE, accuracy=100, max_pp=20)
    HYPER_BEAM = PokemonMoveData(id=0x3f, power=150, ptype=PokemonType.NORMAL, accuracy=90,  max_pp=5)
    PECK = PokemonMoveData(id=0x40, power=35, ptype=PokemonType.FLYING, accuracy=100, max_pp=35)
    DRILL_PECK = PokemonMoveData(id=0x41, power=80, ptype=PokemonType.FLYING, accuracy=100, max_pp=20)
    SUBMISSION = PokemonMoveData(id=0x42, power=80, ptype=PokemonType.FIGHTING, accuracy=80, max_pp=25)
    LOW_KICK = PokemonMoveData(id=0x43, power=50, ptype=PokemonType.FIGHTING, accuracy=90, max_pp=20)
    COUNTER = PokemonMoveData(id=0x44, power=1, ptype=PokemonType.FIGHTING, accuracy=100, max_pp=20)
    SEISMIC_TOSS = PokemonMoveData(id=0x45, power=1, ptype=PokemonType.FIGHTING, accuracy=100, max_pp=20)
    STRENGTH = PokemonMoveData(id=0x46, power=80, ptype=PokemonType.NORMAL, accuracy=100, max_pp=15)
    ABSORB = PokemonMoveData(id=0x47, power=20, ptype=PokemonType.GRASS, accuracy=100, max_pp=20)
    MEGA_DRAIN = PokemonMoveData(id=0x48, power=40, ptype=PokemonType.GRASS, accuracy=100, max_pp=10)
    LEECH_SEED = PokemonMoveData(id=0x49, power=0, ptype=PokemonType.GRASS, accuracy=90, max_pp=10)
    GROWTH = PokemonMoveData(id=0x4a, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=40)
    RAZOR_LEAF = PokemonMoveData(id=0x4b, power=55, ptype=PokemonType.GRASS, accuracy=95, max_pp=25)
    SOLARBEAM = PokemonMoveData(id=0x4c, power=120, ptype=PokemonType.GRASS, accuracy=100, max_pp=10)
    POISONPOWDER = PokemonMoveData(id=0x4d, power=0, ptype=PokemonType.POISON, accuracy=75, max_pp=35)
    STUN_SPORE = PokemonMoveData(id=0x4e, power=0, ptype=PokemonType.GRASS, accuracy=75, max_pp=30)
    SLEEP_POWDER = PokemonMoveData(id=0x4f, power=0, ptype=PokemonType.GRASS, accuracy=75, max_pp=15)
    PETAL_DANCE = PokemonMoveData(id=0x50, power=70, ptype=PokemonType.GRASS, accuracy=100, max_pp=20)
    STRING_SHOT = PokemonMoveData(id=0x51, power=0, ptype=PokemonType.BUG, accuracy=95, max_pp=40)
    DRAGON_RAGE = PokemonMoveData(id=0x52, power=1, ptype=PokemonType.DRAGON, accuracy=100, max_pp=10)
    FIRE_SPIN = PokemonMoveData(id=0x53, power=15, ptype=PokemonType.FIRE, accuracy=70, max_pp=15)
    THUNDERSHOCK = PokemonMoveData(id=0x54, power=40, ptype=PokemonType.ELECTRIC, accuracy=100, max_pp=30)
    THUNDERBOLT = PokemonMoveData(id=0x55, power=95, ptype=PokemonType.ELECTRIC, accuracy=100, max_pp=15)
    THUNDER_WAVE = PokemonMoveData(id=0x56, power=0, ptype=PokemonType.ELECTRIC, accuracy=100, max_pp=20)
    THUNDER = PokemonMoveData(id=0x57, power=120, ptype=PokemonType.ELECTRIC, accuracy=70, max_pp=10)
    ROCK_THROW = PokemonMoveData(id=0x58, power=50, ptype=PokemonType.ROCK, accuracy=65, max_pp=15)
    EARTHQUAKE = PokemonMoveData(id=0x59, power=100, ptype=PokemonType.GROUND, accuracy=100, max_pp=10)
    FISSURE = PokemonMoveData(id=0x5a, power=1, ptype=PokemonType.GROUND, accuracy=30,  max_pp=5)
    DIG = PokemonMoveData(id=0x5b, power=100, ptype=PokemonType.GROUND, accuracy=100, max_pp=10)
    TOXIC = PokemonMoveData(id=0x5c, power=0, ptype=PokemonType.POISON, accuracy=85, max_pp=10)
    CONFUSION = PokemonMoveData(id=0x5d, power=50, ptype=PokemonType.PSYCHIC, accuracy=100, max_pp=25)
    PSYCHIC_M = PokemonMoveData(id=0x5e, power=90, ptype=PokemonType.PSYCHIC, accuracy=100, max_pp=10)
    HYPNOSIS = PokemonMoveData(id=0x5f, power=0, ptype=PokemonType.PSYCHIC, accuracy=60, max_pp=20)
    MEDITATE = PokemonMoveData(id=0x60, power=0, ptype=PokemonType.PSYCHIC, accuracy=100, max_pp=40)
    AGILITY = PokemonMoveData(id=0x61, power=0, ptype=PokemonType.PSYCHIC, accuracy=100, max_pp=30)
    QUICK_ATTACK = PokemonMoveData(id=0x62, power=40, ptype=PokemonType.NORMAL, accuracy=100, max_pp=30)
    RAGE = PokemonMoveData(id=0x63, power=20, ptype=PokemonType.NORMAL, accuracy=100, max_pp=20)
    TELEPORT = PokemonMoveData(id=0x64, power=0, ptype=PokemonType.PSYCHIC, accuracy=100, max_pp=20)
    NIGHT_SHADE = PokemonMoveData(id=0x65, power=0, ptype=PokemonType.GHOST, accuracy=100, max_pp=15)
    MIMIC = PokemonMoveData(id=0x66, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=10)
    SCREECH = PokemonMoveData(id=0x67, power=0, ptype=PokemonType.NORMAL, accuracy=85, max_pp=40)
    DOUBLE_TEAM = PokemonMoveData(id=0x68, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=15)
    RECOVER = PokemonMoveData(id=0x69, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=20)
    HARDEN = PokemonMoveData(id=0x6a, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=30)
    MINIMIZE = PokemonMoveData(id=0x6b, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=20)
    SMOKESCREEN = PokemonMoveData(id=0x6c, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=20)
    CONFUSE_RAY = PokemonMoveData(id=0x6d, power=0, ptype=PokemonType.GHOST, accuracy=100, max_pp=10)
    WITHDRAW = PokemonMoveData(id=0x6e, power=0, ptype=PokemonType.WATER, accuracy=100, max_pp=40)
    DEFENSE_CURL = PokemonMoveData(id=0x6f, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=40)
    BARRIER = PokemonMoveData(id=0x70, power=0, ptype=PokemonType.PSYCHIC, accuracy=100, max_pp=30)
    LIGHT_SCREEN = PokemonMoveData(id=0x71, power=0, ptype=PokemonType.PSYCHIC, accuracy=100, max_pp=30)
    HAZE = PokemonMoveData(id=0x72, power=0, ptype=PokemonType.ICE, accuracy=100, max_pp=30)
    REFLECT = PokemonMoveData(id=0x73, power=0, ptype=PokemonType.PSYCHIC, accuracy=100, max_pp=20)
    FOCUS_ENERGY = PokemonMoveData(id=0x74, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=30)
    BIDE = PokemonMoveData(id=0x75, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=10)
    METRONOME = PokemonMoveData(id=0x76, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=10)
    MIRROR_MOVE = PokemonMoveData(id=0x77, power=0, ptype=PokemonType.FLYING, accuracy=100, max_pp=20)
    SELFDESTRUCT = PokemonMoveData(id=0x78, power=130, ptype=PokemonType.NORMAL, accuracy=100,  max_pp=5)
    EGG_BOMB = PokemonMoveData(id=0x79, power=100, ptype=PokemonType.NORMAL, accuracy=75, max_pp=10)
    LICK = PokemonMoveData(id=0x7a, power=20, ptype=PokemonType.GHOST, accuracy=100, max_pp=30)
    SMOG = PokemonMoveData(id=0x7b, power=20, ptype=PokemonType.POISON, accuracy=70, max_pp=20)
    SLUDGE = PokemonMoveData(id=0x7c, power=65, ptype=PokemonType.POISON, accuracy=100, max_pp=20)
    BONE_CLUB = PokemonMoveData(id=0x7d, power=65, ptype=PokemonType.GROUND, accuracy=85, max_pp=20)
    FIRE_BLAST = PokemonMoveData(id=0x7e, power=120, ptype=PokemonType.FIRE, accuracy=85,  max_pp=5)
    WATERFALL = PokemonMoveData(id=0x7f, power=80, ptype=PokemonType.WATER, accuracy=100, max_pp=15)
    CLAMP = PokemonMoveData(id=0x80, power=35, ptype=PokemonType.WATER, accuracy=75, max_pp=10)
    SWIFT = PokemonMoveData(id=0x81, power=60, ptype=PokemonType.NORMAL, accuracy=100, max_pp=20)
    SKULL_BASH = PokemonMoveData(id=0x82, power=100, ptype=PokemonType.NORMAL, accuracy=100, max_pp=15)
    SPIKE_CANNON = PokemonMoveData(id=0x83, power=20, ptype=PokemonType.NORMAL, accuracy=100, max_pp=15)
    CONSTRICT = PokemonMoveData(id=0x84, power=10, ptype=PokemonType.NORMAL, accuracy=100, max_pp=35)
    AMNESIA = PokemonMoveData(id=0x85, power=0, ptype=PokemonType.PSYCHIC, accuracy=100, max_pp=20)
    KINESIS = PokemonMoveData(id=0x86, power=0, ptype=PokemonType.PSYCHIC, accuracy=80, max_pp=15)
    SOFTBOILED = PokemonMoveData(id=0x87, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=10)
    HI_JUMP_KICK = PokemonMoveData(id=0x88, power=85, ptype=PokemonType.FIGHTING, accuracy=90, max_pp=20)
    GLARE = PokemonMoveData(id=0x89, power=0, ptype=PokemonType.NORMAL, accuracy=75, max_pp=30)
    DREAM_EATER = PokemonMoveData(id=0x8a, power=100, ptype=PokemonType.PSYCHIC, accuracy=100, max_pp=15)
    POISON_GAS = PokemonMoveData(id=0x8b, power=0, ptype=PokemonType.POISON, accuracy=55, max_pp=40)
    BARRAGE = PokemonMoveData(id=0x8c, power=15, ptype=PokemonType.NORMAL, accuracy=85, max_pp=20)
    LEECH_LIFE = PokemonMoveData(id=0x8d, power=20, ptype=PokemonType.BUG, accuracy=100, max_pp=15)
    LOVELY_KISS = PokemonMoveData(id=0x8e, power=0, ptype=PokemonType.NORMAL, accuracy=75, max_pp=10)
    SKY_ATTACK = PokemonMoveData(id=0x8f, power=140, ptype=PokemonType.FLYING, accuracy=90,  max_pp=5)
    TRANSFORM = PokemonMoveData(id=0x90, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=10)
    BUBBLE = PokemonMoveData(id=0x91, power=20, ptype=PokemonType.WATER, accuracy=100, max_pp=30)
    DIZZY_PUNCH = PokemonMoveData(id=0x92, power=70, ptype=PokemonType.NORMAL, accuracy=100, max_pp=10)
    SPORE = PokemonMoveData(id=0x93, power=0, ptype=PokemonType.GRASS, accuracy=100, max_pp=15)
    FLASH = PokemonMoveData(id=0x94, power=0, ptype=PokemonType.NORMAL, accuracy=70, max_pp=20)
    PSYWAVE = PokemonMoveData(id=0x95, power=1, ptype=PokemonType.PSYCHIC, accuracy=80, max_pp=15)
    SPLASH = PokemonMoveData(id=0x96, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=40)
    ACID_ARMOR = PokemonMoveData(id=0x97, power=0, ptype=PokemonType.POISON, accuracy=100, max_pp=40)
    CRABHAMMER = PokemonMoveData(id=0x98, power=90, ptype=PokemonType.WATER, accuracy=85, max_pp=10)
    EXPLOSION = PokemonMoveData(id=0x99, power=170, ptype=PokemonType.NORMAL, accuracy=100,  max_pp=5)
    FURY_SWIPES = PokemonMoveData(id=0x9a, power=18, ptype=PokemonType.NORMAL, accuracy=80, max_pp=15)
    BONEMERANG = PokemonMoveData(id=0x9b, power=50, ptype=PokemonType.GROUND, accuracy=90, max_pp=10)
    REST = PokemonMoveData(id=0x9c, power=0, ptype=PokemonType.PSYCHIC, accuracy=100, max_pp=10)
    ROCK_SLIDE = PokemonMoveData(id=0x9d, power=75, ptype=PokemonType.ROCK, accuracy=90, max_pp=10)
    HYPER_FANG = PokemonMoveData(id=0x9e, power=80, ptype=PokemonType.NORMAL, accuracy=90, max_pp=15)
    SHARPEN = PokemonMoveData(id=0x9f, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=30)
    CONVERSION = PokemonMoveData(id=0xa0, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=30)
    TRI_ATTACK = PokemonMoveData(id=0xa1, power=80, ptype=PokemonType.NORMAL, accuracy=100, max_pp=10)
    SUPER_FANG = PokemonMoveData(id=0xa2, power=1, ptype=PokemonType.NORMAL, accuracy=90, max_pp=10)
    SLASH = PokemonMoveData(id=0xa3, power=70, ptype=PokemonType.NORMAL, accuracy=100, max_pp=20)
    SUBSTITUTE = PokemonMoveData(id=0xa4, power=0, ptype=PokemonType.NORMAL, accuracy=100, max_pp=10)
    STRUGGLE = PokemonMoveData(id=0xa5, power=50, ptype=PokemonType.NORMAL, accuracy=100, max_pp=10)


    @classmethod
    def from_byte_or_none(cls, byte_value):
        return cls(byte_value) if byte_value in cls._value2member_map_ else None


MOVE_BY_ID = {move.value.id: move for move in PokemonMoves}
